### ISSUE TITLE
Explain the phpBB upgrade fix in better English

### ISSUE THREAD

**Issue by maliktunga** [maliktunga/phpbb-openshift-quickstart#2]
The README.md only says "Delete the php/install/ directory" when it comes to applying [the fix for the upgrade to 3.1.2](https://www.phpbb.com/support/docs/en/3.1/ug/upgradeguide/upgrade3/). Either the step should be better explained (preferably with console commands), either it should be replaced with a direct fix.

**Comment by jekader** [comment]
From what I understand this fork ships 3.1.2 codebase, yet the database dump [1] is from 3.0.8 and some manual upgrades are required to bump the version. I think that's not the way to go.

The simplest fix is to just install 3.0.8, perform update manually and dump the resulting DB replacing the current phpbb.sql

The correct way IMHO would be to actually run the logic from [2] at each deploy to generate the DB from scratch.

[1] https://github.com/maliktunga/phpbb-openshift-quickstart/blob/master/.openshift/action_hooks/phpbb.sql
[2] https://github.com/maliktunga/phpbb-openshift-quickstart/blob/master/php/install/install_install.php

**Comment by maliktunga** [comment]
@jekader Could you try that for me please? I don't know where to find the DB.

**Comment by maliktunga** [comment]
@jekader Also yes, it does ship with the latest 3.1.2 codebase.

**Comment by maliktunga** [comment]
@jekader And the current database dump is from 3.0.9.

**Comment by jekader** [comment]
To dump the DB it's basically enough to SSH into the gear and run:

mysqldump -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" $OPENSHIFT_APP_NAME > php/tmp/phpbb.sql

I've dumped a DB of a fresh install+upgrade, let me create a pull request

**Comment by maliktunga** [comment]
@jekader I see, go ahead for the pull request!

**Comment by maliktunga** [comment]
Fixed with pull request https://github.com/maliktunga/phpbb-openshift-quickstart/pull/3. I also deleted the install directory.
